---
# Description
- name: Description of the playbook
  hosts: all
  gather_facts: true
  tasks:
    - name: Install dhcp
      yum:
        name: dhcp-server
        state: present
    - name: Copy dhcpd.conf
      copy:
        src: /root/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
    - name: Start dhcp
      service:
        name: dhcpd
        state: started
        enabled: true
    - name: Firewall for dhcp
      # Comment
      ansible.posix.firewalld:
        service: dhcp
        permanent: true
        state: enabled
        immediate: true
    - name: Restart dhcp
      service:
        name: dhcpd
        state: restarted