# code: language=ansible
- name: Install and configure services
  hosts: servers
  become: yes
  become_method: sudo
  become_user: root
  become_flags: '-H'

  vars_files:
    - all_variables.yml

  tasks:
    - name: Add users 
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop: "{{ linux_users }}"

    - name: Install required packages
      ansible.builtin.dnf:      
            name: "{{ item }}"
      loop:
            - samba
            - dhcp-server
            - httpd
            - bind
            - mariadb-server
            - php
            - php-mysqlnd
            - php-gd
            - php-mbstring
            - php-xml
            - php-json
            - php-pear
            - php-fpm
            - php-opcache
            - nfs-utils

    - name: Configure dhcpd.conf
      ansible.builtin.template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        mode: 420
        owner: root
        group: root

    - name: Configure named.conf
      ansible.builtin.template:
        src: named.conf.j2
        dest: /etc/named.conf
        mode: 420
        owner: root
        group: root
      with_items: "{{ domains }}"

    - name: Generate zone files
      ansible.builtin.template:
        src: "domain.com.zone.j2"
        dest: "/var/named/{{ item.name }}.db"
        mode: 420
        owner: named
        group: named
      with_items: "{{ domains }}"
    
    - name: Generate create folders
      ansible.builtin.file:
        path: "{{ item.folder }}"
        state: directory
        mode: 777
        owner: nfsnobody
        group: nfsnobody
      with_items: "{{ nfs }}"

    - name: Generate /etc/exports file
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports
        mode: 644
        owner: root
        group: root
      with_items: "{{ nfs }}"

    - name: Include Samba Server role
      ansible.builtin.include_role:
          name: vladgh.samba.server

    - name: Include role
      ansible.builtin.include_role:
        name: vladgh.samba.server
      vars:
        samba_netbios_name: "{{ samba_netbios_name }}"
        samba_server_string: "{{ samba_description }}"
        samba_workgroup: "{{ samba_workgroup }}"
        samba_load_homes: true
        samba_load_printers: false
        with_items: "{{ samba_config }}"

        samba_users:
          - name: "{{ item.name }}"
            password: "{{ item.password }} "
            with_items: "{{ samba_users }}"

        samba_shares_root: /srv/samba
        samba_shares:
          - name: "{{item.name}}"
            comment: "{{item.comment}}"
            valid_users: "{{item.valid_users}}"
            write_list: "{{item.write_list}}" 
            group: "{{item.group}}"
            browseable: '{{item.browseable}}'
            public: '{{item.public}}'
            guest_ok: '{{item.guest_ok}}'
            read_only: '{{item.read_only}}'
            create_mask: '{{item.create_mask}}'
            directory_mask: '{{item.directory_mask}}'
            force_create_mode: '{{item.force_create_mode}}'
            force_directory_mode: '{{item.force_directory_mode}}'
            force_user: '{{item.force_user}}'
            force_group: '{{item.force_group}}'
            with_items: "{{ samba_shares }}"

        
    - name: create file folder an create index for domains
      ansible.builtin.file:
        path: /srv/{{item.name}}/index.php
        state: touch
        mode: 755
        owner: apache
        group: apache
      with_items: "{{ domains }}"



    - name: httpd.conf.d using variables for virtual hosts
      template:
          src: virtual.conf.j2
          dest: /etc/httpd/conf/httpd.conf.d/{{ item.name }}.conf
          mode: 644
          owner: root
          group: root
      with_items: "{{ domains }}"


    - name: start and enable services
      service:
            name: "{{ item }}"
            state: started
            enabled: true
      loop:
            - smb
            - nmb
            - dhcpd
            - httpd
            - named
            - mariadb
            - php-fpm

    - name: Open Services
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https
        - nfs
        - samba
        - dhcp
        - dns
        - mysql
        
    - name: Firewalld Open ports
      ansible.builtin.firewalld:
            port: "{{ item }}"
            permanent: true
            state: enabled
            immediate: true
      loop:
            - 137/tcp
            - 138/tcp
            - 139/tcp
            - 445/tcp
            - 67/udp
            - 68/udp
            - 80/tcp
            - 443/tcp
            - 53/tcp
            - 53/udp
            - 3306/tcp


