# code: language=ansible
- name: Install and configure services
  hosts: servers
  become: true
  vars_files:
    - dhcp_vars.yml
    - named_vars.yml
    - samba_vars.yml
    - httpd_vars.yml
    - nfs_vars.yml

  tasks:
    - name: Add users 
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        with_items: "{{ linux_users }}"

    - name: Install required packages
      yum:
            name: "{{ item }}"
            state: present
      loop:
            - samba
            - dhcp-server
            - httpd
            - bind
            - mariadb-server
            - php
            - php-mysqlnd
            - php-gd
            - php-mbstring
            - php-xml
            - php-json
            - php-pear
            - php-fpm
            - php-opcache
            - nfs-server


    - name: Open necessary ports in firewall
       hosts= servers
      firewalld:
            port: "{{ item }}"
            permanent: true
            state: enabled
            immediate: true
      loop:
            - 137/tcp
            - 138/tcp
            - 139/tcp
            - 445/tcp
            - 67/udp
            - 68/udp
            - 80/tcp
            - 443/tcp
            - 53/tcp
            - 53/udp
            - 3306/tcp

    - name: Configure dhcpd.conf
      ansible.builtin.template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        mode: 420
        owner: root
        group: root
      notify: restart dhcpd    
      
    - name: Configure named.conf
      ansible.builtin.template:
        src: named.conf.j2
        dest: /etc/named.conf
        mode: 420
        owner: root
        group: root
      notify: restart named
      with_items: "{{ domains }}"

    - name: Generate zone files
      ansible.builtin.template:
        src: "{{ item.name }}.zone.j2"
        dest: "/var/named/{{ item.name }}.db"
        mode: 420
        owner: named
        group: named
      with_items: "{{ domains }}"
    
    - name: Generate create folders
      ansible.builtin.file:
        path: "{{ item.folder }}"
        state: directory
        mode: 777
        owner: nfsnobody
        group: nfsnobody
      with_items: "{{ nfs }}"

    - name: Generate /etc/exports file
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports
        mode: 644
        owner: root
        group: root
      with_items: "{{ nfs }}"

    - name: configure samba on smb.conf
      community.general.ini_file:
          path: /etc/samba/smb.conf
          section: global
          option: "{{ item.option }}"
          value: "{{ item.value }}"
      loop:
          - option: workgroup
            value: {{ samba_workgroup }}
          - option: alias
            value: {{ samba_alias }}
          - option: security
            value: {{ samba_security }}
          - option: map to guest
            value: {{ samba_map_to_guest }}
          - option: guest account
            value: {{ samba_guest_account }}
      with_items: "{{ samba_config }}"

    - name: samba user
      user:
            name: "{{ item.name }}"
            password: "{{ item.password }}"
            state: present
      loop: "{{ samba_users }}"
        
    - name: configure samba on smb.conf
      community.general.ini_file:
          path: /etc/samba/smb.conf
          section: [global]
          option: "{{ item.option }}"
          value: "{{ item.value }}"
          backup: yes
      loop: "{{ samba_config }}"

    - name: configure samba shares
      community.general.ini_file:
          path: /etc/samba/smb.conf
          section: "{{ item.section }}"
          option: "{{ item.option }}"
          value: "{{ item.value }}"
      loop: "{{ samba_shares }}"

    - name: Generate create folders
      ansible.builtin.file:
        path: "{{ item.option }}"
        state: directory
        mode: 777
        owner: root
        group: root
      with_items: "{{ samba_folders }}"
        
    - name: create file folder an create index for domains
      ansible.builtin.file:
        path: /srv/{{item.name}}/index.php
        state: touch
        mode: 755
        owner: apache
        group: apache
      with_items: "{{ domains }}"



    - name: httpd.conf.d using variables for virtual hosts
      template:
          src: virtual.conf.j2
          dest: /etc/httpd/conf/httpd.conf.d/{{ item.name }}.conf
          mode: 644
          owner: root
          group: root
      with_items: "{{ domains }}"

      
    - name: Apply SELinux policies
      selinux:
            policy: targeted
            state: disabled

    - name: start and enable services
      service:
            name: "{{ item }}"
            state: started
            enabled: true
      loop:
            - smb
            - nmb
            - dhcpd
            - httpd
            - named
            - mariadb
            - php-fpm


- name: create database
  mysql_db:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ databases }}"



