# code: language=ansible
- name: Install and configure services
  hosts: servers
  become: yes
  become_method: sudo
  become_user: root
  become_flags: '-H'

  vars_files:
    - all_variables.yml

  tasks:
    - name: Add users 
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop: "{{ linux_users }}"

    - name: Install required packages
      ansible.builtin.dnf:      
            name: "{{ item }}"
      loop:
            - samba
            - dhcp-server
            - httpd
            - bind

            - nfs-utils

    - name: Configure dhcpd.conf
      ansible.builtin.template:
        src: dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        mode: 420
        owner: root
        group: root
        

    - name: Configure named.conf
      ansible.builtin.template:
        src: named.conf.j2
        dest: /etc/named.conf
        mode: 420
        owner: root
        group: root
      with_items: "{{ domains }}"


    - name: Generate zone files
      ansible.builtin.template:
        src: "domain.com.zone.j2"
        dest: "/var/named/{{ item.name }}.db"
        mode: 420
        owner: named
        group: named
      with_items: "{{ domains }}"
    
    - name: Generate create NFS folders
      file:
        path: "/nfs_share"
        state: directory
        mode: !!str 777
        owner: nobody
        group: nobody
      
    
    - name: Generate /etc/exports file
      ansible.builtin.template:
        src: exports.j2
        dest: /etc/exports
        mode: 644
        owner: root
        group: root
      with_items: "{{ nfs }}"

    - name: Include Samba Server role
      ansible.builtin.include_role:
          name: vladgh.samba.server

    - name: Include role
      ansible.builtin.include_role:
        name: vladgh.samba.server
      vars:
        samba_workgroup: WORKGROUP
        samba_server_string: "Samba Server"
        samba_mdns_name: "Samba Server"
        samba_security: user
        samba_bind_interfaces_only: yes
        samba_load_homes: yes
        samba_passdb_backend: tdbsam
        samba_map_to_guest: bad user
        samba_domain_master: yes
        samba_dns_proxy: no
        samba_log_level: 1
        samba_log_file: /var/log/samba/%m.log
        samba_max_log_size: 50
        samba_printing: cups
        samba_printcap_name: cups
        samba_printing_bsd: cups
        samba_printing_cups: cups
        samba_printing_lprng: cups
        samba_disable_spoolss: yes
        samba_load_printers: yes
        samba_print_driver: cups
        samba_print_driver_dir: /usr/share/cups/drivers
        samba_shares_global:
          - name: homes
            comment: Home Directories
            browseable: no
            writable: yes
            valid_users: "%S"
            create_mask: 0700
            directory_mask: 0700
        samba_users:
          - name: "{{ item.name }}"
            password: "{{ item.password }} "
            with_items: "{{ samba_users }}"
        samba_shares_users:
          - name: "{{item.name}}"
            comment: "{{item.comment}}"
            valid_users: "{{item.valid_users}}"
            write_list: "{{item.write_list}}" 
            group: "{{item.group}}"
            browseable: '{{item.browseable}}'
            public: '{{item.public}}'
            guest_ok: '{{item.guest_ok}}'
            read_only: '{{item.read_only}}'
            create_mask: '{{item.create_mask}}'
            directory_mask: '{{item.directory_mask}}'
            force_create_mode: '{{item.force_create_mode}}'
            force_directory_mode: '{{item.force_directory_mode}}'
            force_user: '{{item.force_user}}'
            force_group: '{{item.force_group}}'
            with_items: "{{ samba_shares }}"
          

        
    - name: create file folder an create index for domains
      ansible.builtin.file:
        path: /srv/{{item.name}}/
        state: directory
        mode: !!str 755
        owner: apache
        group: apache
      loop: "{{ domains }}"

    - name: insert text to file
      ansible.builtin.lineinfile:
        path: /srv/{{item.name}}/public_html/index.html
        line: "{{item.name}}"
        mode: !!str 755
        owner: apache
        group: apache
        create: yes
      loop: "{{ domains }}"
     


    - name: httpd.conf.d using variables for virtual hosts
      template:
          src: virtual.conf.j2
          dest: /etc/httpd/conf.d/{{ item.name }}.conf
          mode: 644
          owner: root
          group: root
      with_items: "{{ domains }}"


    - name: start and enable services 
      service:
            name: "{{ item }}"
            state: restarted
            enabled: true
      loop:
            - smb
            - nmb
            - dhcpd
            - httpd
            - named
            - nfs-server
                        

    - name: Open Services
      ansible.builtin.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https
        - nfs
        - samba
        - dhcp
        - dns
        - mysql
        - mountd
        - rpc-bind
        
    - name: Firewalld Open ports
      ansible.builtin.firewalld:
            port: "{{ item }}"
            permanent: true
            state: enabled
            immediate: true
      loop:
            - 137/tcp
            - 138/tcp
            - 139/tcp
            - 445/tcp
            - 67/udp
            - 68/udp
            - 80/tcp
            - 443/tcp
            - 53/tcp
            - 53/udp
            - 3306/tcp
            - 111/tcp
            - 111/udp

    


    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:

    - name: Wait for the machine to reboot
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 300
    
    
    - name: disable ethernet interfase nmcli 
      community.general.nmcli:
        conn_name: "{{ item }}"
        state: absent
      loop:
        - enp2s0